### ISSUE TITLE
[TODO] : 환경변수들(profile) 외부주입으로 되게끔 수정.

### ISSUE THREAD

**Issue by shininghyunho** [krescere/jipsayo-backend#22]
예전에 안되서 private 바꿨다가 다시 public으로 바꿨음.
그래서 private key 오픈되서 deprecated 시킴.
새로 하나 만들어서 외부 주입으로 변경.

**Comment by shininghyunho** [comment]
# github secret 키로 변수 주입
```bash
    # set rds yaml
    - name: Set RDS YAML
      uses: microsoft/variable-substitution@v1
      with:
        files: './src/main/resources/application-rds.yml'
      env:
        spring.datasource.url: ${{ secrets.RDS_URL }}
        spring.datasource.hikari.username: ${{ secrets.RDS_USERNAME }}
        spring.datasource.hikari.password: ${{ secrets.RDS_PASSWORD }}

```

문제없이 동작

그러나 local 에서 동작시 매번 아래 사항을 입력해줘야함.
```yaml
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${RDS_URL}
    hikari:
      username: ${RDS_USERNAME}
      password: ${RDS_PASSWORD}
```
